# ==============================================================================
# 04_validation.R
# PURPOSE: Validate the geocoded coordinates generated by 03_geocoding.R
# ==============================================================================

library(tidyverse)
library(ggplot2)

# Load coordinates generated from 03_geocoding.R
coords <- read_csv("data/hdb_coordinates.csv")
head(coords)

# Check for NA values
missing_coords <- coords %>% filter(is.na(lat) | is.na(long))

if (nrow(missing_coords) > 0) {
  print(paste("ERROR:", nrow(missing_coords), "addresses with missing coordinates"))
  print(head(missing_coords))
} else {
  print(paste(nrow(coords), "valid coordinates generated"))
}

# Verify all addresses from cleaned dataset have correctly been converted to coordinates
cleaned_data <- read_csv("data/cleaned_resale_prices.csv")

# Create column of unique addresses
unique_addresses <- cleaned_data %>%
  mutate(search_address = paste(block, street_name)) %>%
  select(search_address) %>%
  distinct(search_address)

n_addresses <- nrow(unique_addresses)
n_coords <- nrow(coords)

print(paste("Unique Addresses from cleaned dataset:", n_addresses))
print(paste("Rows in Geocoded data:", n_coords))


# Plot a scatterplot of x and y coords to see distribution of coordinates
# Ensure that the coords collectively look roughly like Singapore so we didn't mess up
ggplot(coords, aes(x = long, y = lat)) +
  geom_point(alpha = 0.3, size = 0.5, color = "slateblue") +
  theme_minimal() +
  labs(
    title = "Scatterplot of Coordinates",
    x = "Longitude",
    y = "Latitude"
  ) +
  coord_fixed() # keeps the aspect ratio fixed (don't squeeze it)